"$schema" = 'https://starship.rs/config-schema.json'

format = """
${hostname}\
${directory}\
[](fg:#404040)\
"""

[hostname]
style = "bg:#404040 fg:#00ffff"
format = "[ $hostname ]($style)"


[directory]
style = "bg:#404040 fg:#00ffff"
format = "[ $path ]($style)"
truncate_to_repo = false
