format = """
${custom.hostname}\
${custom.hostnameDev}\
${custom.hostnameCRM}\
${custom.directory}\
${custom.directoryDev}\
${custom.directoryCRM}\
[](fg:#404040)\
"""

[custom.hostname]
command = """ 
if [[ "$(hostname)" == "jonny-archbook" ]]; then 
  echo "$(hostname) " 
fi 
"""
when = """ 
if [[ "$(hostname)" == "jonny-archbook" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#00ffff"
format = "[ $output ]($style)"

[custom.hostnameDev]
command = """ 
if [[ "$(hostname)" == "CRM-Dev" ]]; then 
  echo "$(hostname) " 
fi 
"""
when = """ 
if [[ "$(hostname)" == "CRM-Dev" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#00ff00"
format = "[ $output ]($style)"

[custom.hostnameCRM]
command = """ 
if [[ "$(hostname)" == "CRM-Extended" ]]; then 
  echo "$(hostname) " 
fi 
"""
when = """ 
if [[ "$(hostname)" == "CRM-Extended" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#ff0000"
format = "[ $output ]($style)"

[custom.directory]
command = """ 
if [[ "$(hostname)" == "jonny-archbook" ]]; then 
  dirs -p | head -n 1
fi 
"""
when = """ 
if [[ "$(hostname)" == "jonny-archbook" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#00ffff"
format = "[$output ]($style)"

[custom.directoryDev]
command = """ 
if [[ "$(hostname)" == "CRM-Dev" ]]; then 
  dirs -p | head -n 1
fi 
"""
when = """ 
if [[ "$(hostname)" == "CRM-Dev" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#00ff00"
format = "[$output ]($style)"

[custom.directoryCRM]
command = """ 
if [[ "$(hostname)" == "CRM-Extended" ]]; then 
  dirs -p | head -n 1
fi 
"""
when = """ 
if [[ "$(hostname)" == "CRM-Extended" ]]; then 
  true
else 
  false
fi 
"""
style = "bg:#404040 fg:#ff0000"
format = "[$output ]($style)"
